services:
  firestore-emulator:
    image: google/cloud-sdk:latest
    platform: linux/amd64
    command: >
      gcloud emulators firestore start
      --host-port=0.0.0.0:8081
      --project=michinori-local
    ports:
      - "8081:8081"
